package net.cosmosfury.divinefavours.datagen;

import net.cosmosfury.divinefavours.DivineFavours;
import net.cosmosfury.divinefavours.block.blockregistry;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.tags.BlockTags;
import net.minecraftforge.common.Tags;
import net.minecraftforge.common.data.BlockTagsProvider;
import net.minecraftforge.common.data.ExistingFileHelper;
import org.jetbrains.annotations.Nullable;

import java.util.concurrent.CompletableFuture;

public class blocktaggenerator extends BlockTagsProvider {
    public blocktaggenerator(PackOutput output, CompletableFuture<HolderLookup.Provider> lookupProvider, @Nullable ExistingFileHelper existingFileHelper) {
        super(output, lookupProvider, DivineFavours.MOD_ID, existingFileHelper);
    }

    @Override
    protected void addTags(HolderLookup.Provider pProvider) {


        this.tag(BlockTags.MINEABLE_WITH_PICKAXE)
                .add(blockregistry.UNCUT_SAPPHIRE_PILLAR.get(),
                        blockregistry.UNCUT_RUBY_PILLAR.get(),
                        blockregistry.UNCUT_JADE_PILLAR.get(),
                        blockregistry.UNCUT_TOPAZ_PILLAR.get(),
                        blockregistry.UNCUT_SAPPHIRE_NODE.get(),
                        blockregistry.UNCUT_MOONSTONE_PILLAR.get(),
                        blockregistry.UNCUT_MOONSTONE_NODE.get(),
                        blockregistry.UNCUT_RUBY_NODE.get(),
                        blockregistry.UNCUT_JADE_NODE.get(),
                        blockregistry.UNCUT_TOPAZ_NODE.get(),
                        blockregistry.MITHRIL_ORE.get(),
                        blockregistry.DEEPSLATE_MITHRIL_ORE.get(),
                        blockregistry.MITHRIL_BLOCK.get(),
                        blockregistry.RAW_MITHRIL_BLOCK.get(),
                        blockregistry.BRAZIER_MITHRIL.get(),
                        blockregistry.BRAZIER_ASTRALITE.get(),
                        blockregistry.BRAZIER_GLEAMIUM.get(),
                        blockregistry.BRAZIER_KYBER.get(),
                        blockregistry.BRAZIER_ORICHALCUM.get(),
                        blockregistry.BRAZIER_PROMETHEUM.get(),
                        blockregistry.BRAZIER_QUASARITE.get(),
                        blockregistry.BRAZIER_WYRMSTONE.get(),
                        blockregistry.ORICHALCUM_BLOCK.get(),
                        blockregistry.ASTRALITE_BLOCK.get(),
                        blockregistry.RAW_ASTRALITE_BLOCK.get(),
                        blockregistry.GLEAMIUM_BLOCK.get(),
                        blockregistry.RAW_GLEAMIUM_BLOCK.get(),
                        blockregistry.KYBER_BLOCK.get(),
                        blockregistry.KYBER_ORE.get(),
                        blockregistry.RAW_KYBER_BLOCK.get(),
                        blockregistry.ORICHALCUM_ORE.get(),
                        blockregistry.RAW_ORICHALCUM_BLOCK.get(),
                        blockregistry.PROMETHEUM_BLOCK.get(),
                        blockregistry.PROMETHEUM_ORE.get(),
                        blockregistry.RAW_PROMETHEUM_BLOCK.get(),
                        blockregistry.QUASARITE_BLOCK.get(),
                        blockregistry.WYRMSTONE_BLOCK.get(),
                        blockregistry.SAPPHIRE_ALTAR.get(),
                        blockregistry.RUBY_ALTAR.get(),
                        blockregistry.JADE_ALTAR.get(),
                        blockregistry.TOPAZ_ALTAR.get(),
                        blockregistry.CROWN_ALTAR.get(),
                        blockregistry.TABLET_STAND.get(),
                        blockregistry.SILVER_ORE.get(),
                        blockregistry.DEEPSLATE_SILVER_ORE.get(),
                        blockregistry.SILVER_BLOCK.get(),
                        blockregistry.RAW_SILVER_BLOCK.get(),
                        blockregistry.SILVER_KALVIS_ALTAR.get(),
                        blockregistry.PROMETHEUM_KALVIS_ALTAR.get(),
                        blockregistry.GLEAMIUM_KALVIS_ALTAR.get(),
                        blockregistry.JANUS_TABLE.get(),
                        blockregistry.LIMESTONE_ARCHED_RAILING.get(),
                        blockregistry.LIMESTONE_GLASS_RAILING.get(),
                        blockregistry.LIMESTONE_SIMPLE_RAILING.get(),
                        blockregistry.DEEPSLATE_ARCHED_RAILING.get(),
                        blockregistry.DEEPSLATE_GLASS_RAILING.get(),
                        blockregistry.DEEPSLATE_GLASS_RAILING_A.get(),
                        blockregistry.DEEPSLATE_GLASS_RAILING_B.get(),
                        blockregistry.DEEPSLATE_GLASS_RAILING_C.get(),
                        blockregistry.DEEPSLATE_GLASS_RAILING_D.get(),
                        blockregistry.DEEPSLATE_SIMPLE_RAILING.get(),
                        blockregistry.ANDESITE_ARCHED_RAILING.get(),
                        blockregistry.ANDESITE_GLASS_RAILING.get(),
                        blockregistry.ANDESITE_SIMPLE_RAILING.get(),
                        blockregistry.BRICK_ARCHED_RAILING.get(),
                        blockregistry.BRICK_GLASS_RAILING.get(),
                        blockregistry.BRICK_SIMPLE_RAILING.get(),
                        blockregistry.MUD_BRICK_ARCHED_RAILING.get(),
                        blockregistry.MUD_BRICK_GLASS_RAILING.get(),
                        blockregistry.MUD_BRICK_SIMPLE_RAILING.get(),
                        blockregistry.STONE_ARCHED_RAILING.get(),
                        blockregistry.STONE_GLASS_RAILING.get(),
                        blockregistry.STONE_SIMPLE_RAILING.get(),
                        blockregistry.ANDESITE_GLASS_RAILING_A.get(),
                        blockregistry.ANDESITE_GLASS_RAILING_B.get(),
                        blockregistry.ANDESITE_GLASS_RAILING_C.get(),
                        blockregistry.ANDESITE_GLASS_RAILING_D.get(),
                        blockregistry.ANDESITE_GLASS_RAILING_E.get(),
                        blockregistry.ANDESITE_GLASS_RAILING_F.get(),
                        blockregistry.ANDESITE_GLASS_RAILING_G.get(),
                        blockregistry.ANDESITE_GLASS_RAILING_H.get(),
                        blockregistry.ANDESITE_GLASS_RAILING_I.get(),
                        blockregistry.ANDESITE_ARCHED_RAILING_A.get(),
                        blockregistry.ANDESITE_ARCHED_RAILING_B.get(),
                        blockregistry.ANDESITE_ARCHED_RAILING_C.get(),
                        blockregistry.ANDESITE_ARCHED_RAILING_D.get(),
                        blockregistry.ANDESITE_ARCHED_RAILING_E.get(),
                        blockregistry.ANDESITE_ARCHED_RAILING_F.get(),
                        blockregistry.ANDESITE_ARCHED_RAILING_G.get(),
                        blockregistry.ANDESITE_ARCHED_RAILING_H.get(),
                        blockregistry.ANDESITE_ARCHED_RAILING_I.get(),
                        blockregistry.ANDESITE_SIMPLE_RAILING_A.get(),
                        blockregistry.ANDESITE_SIMPLE_RAILING_B.get(),
                        blockregistry.ANDESITE_SIMPLE_RAILING_C.get(),
                        blockregistry.ANDESITE_SIMPLE_RAILING_D.get(),
                        blockregistry.ANDESITE_SIMPLE_RAILING_E.get(),
                        blockregistry.ANDESITE_SIMPLE_RAILING_F.get(),
                        blockregistry.ANDESITE_SIMPLE_RAILING_G.get(),
                        blockregistry.ANDESITE_SIMPLE_RAILING_H.get(),
                        blockregistry.ANDESITE_SIMPLE_RAILING_I.get(),
                        blockregistry.BRICK_GLASS_RAILING_A.get(),
                        blockregistry.BRICK_GLASS_RAILING_B.get(),
                        blockregistry.BRICK_GLASS_RAILING_C.get(),
                        blockregistry.BRICK_GLASS_RAILING_D.get(),
                        blockregistry.BRICK_GLASS_RAILING_E.get(),
                        blockregistry.BRICK_GLASS_RAILING_F.get(),
                        blockregistry.BRICK_GLASS_RAILING_G.get(),
                        blockregistry.BRICK_GLASS_RAILING_H.get(),
                        blockregistry.BRICK_GLASS_RAILING_I.get(),
                        blockregistry.BRICK_ARCHED_RAILING_A.get(),
                        blockregistry.BRICK_ARCHED_RAILING_B.get(),
                        blockregistry.BRICK_ARCHED_RAILING_C.get(),
                        blockregistry.BRICK_ARCHED_RAILING_D.get(),
                        blockregistry.BRICK_ARCHED_RAILING_E.get(),
                        blockregistry.BRICK_ARCHED_RAILING_F.get(),
                        blockregistry.BRICK_ARCHED_RAILING_G.get(),
                        blockregistry.BRICK_ARCHED_RAILING_H.get(),
                        blockregistry.BRICK_ARCHED_RAILING_I.get(),
                        blockregistry.BRICK_SIMPLE_RAILING_A.get(),
                        blockregistry.BRICK_SIMPLE_RAILING_B.get(),
                        blockregistry.BRICK_SIMPLE_RAILING_C.get(),
                        blockregistry.BRICK_SIMPLE_RAILING_D.get(),
                        blockregistry.BRICK_SIMPLE_RAILING_E.get(),
                        blockregistry.BRICK_SIMPLE_RAILING_F.get(),
                        blockregistry.BRICK_SIMPLE_RAILING_G.get(),
                        blockregistry.BRICK_SIMPLE_RAILING_H.get(),
                        blockregistry.BRICK_SIMPLE_RAILING_I.get(),
                        blockregistry.LIMESTONE_GLASS_RAILING_A.get(),
                        blockregistry.LIMESTONE_GLASS_RAILING_B.get(),
                        blockregistry.LIMESTONE_GLASS_RAILING_C.get(),
                        blockregistry.LIMESTONE_GLASS_RAILING_D.get(),
                        blockregistry.LIMESTONE_GLASS_RAILING_E.get(),
                        blockregistry.LIMESTONE_GLASS_RAILING_F.get(),
                        blockregistry.LIMESTONE_GLASS_RAILING_G.get(),
                        blockregistry.LIMESTONE_GLASS_RAILING_H.get(),
                        blockregistry.LIMESTONE_GLASS_RAILING_I.get(),
                        blockregistry.LIMESTONE_ARCHED_RAILING_A.get(),
                        blockregistry.LIMESTONE_ARCHED_RAILING_B.get(),
                        blockregistry.LIMESTONE_ARCHED_RAILING_C.get(),
                        blockregistry.LIMESTONE_ARCHED_RAILING_D.get(),
                        blockregistry.LIMESTONE_ARCHED_RAILING_E.get(),
                        blockregistry.LIMESTONE_ARCHED_RAILING_F.get(),
                        blockregistry.LIMESTONE_ARCHED_RAILING_G.get(),
                        blockregistry.LIMESTONE_ARCHED_RAILING_H.get(),
                        blockregistry.LIMESTONE_ARCHED_RAILING_I.get(),
                        blockregistry.LIMESTONE_SIMPLE_RAILING_A.get(),
                        blockregistry.LIMESTONE_SIMPLE_RAILING_B.get(),
                        blockregistry.LIMESTONE_SIMPLE_RAILING_C.get(),
                        blockregistry.LIMESTONE_SIMPLE_RAILING_D.get(),
                        blockregistry.LIMESTONE_SIMPLE_RAILING_E.get(),
                        blockregistry.LIMESTONE_SIMPLE_RAILING_F.get(),
                        blockregistry.LIMESTONE_SIMPLE_RAILING_G.get(),
                        blockregistry.LIMESTONE_SIMPLE_RAILING_H.get(),
                        blockregistry.LIMESTONE_SIMPLE_RAILING_I.get(),
                        blockregistry.STONE_GLASS_RAILING_A.get(),
                        blockregistry.STONE_GLASS_RAILING_B.get(),
                        blockregistry.STONE_GLASS_RAILING_C.get(),
                        blockregistry.STONE_ARCHED_RAILING_A.get(),
                        blockregistry.STONE_ARCHED_RAILING_B.get(),
                        blockregistry.STONE_ARCHED_RAILING_C.get(),
                        blockregistry.STONE_SIMPLE_RAILING_A.get(),
                        blockregistry.STONE_SIMPLE_RAILING_B.get(),
                        blockregistry.STONE_SIMPLE_RAILING_C.get(),
                        blockregistry.STONE_ARCHED_RAILING_D.get(),
                        blockregistry.STONE_ARCHED_RAILING_E.get(),
                        blockregistry.STONE_GLASS_RAILING_D.get(),
                        blockregistry.STONE_GLASS_RAILING_E.get(),
                        blockregistry.STONE_SIMPLE_RAILING_D.get(),
                        blockregistry.STONE_SIMPLE_RAILING_E.get(),
                        blockregistry.DEEPSLATE_ARCHED_RAILING_A.get(),
                        blockregistry.DEEPSLATE_ARCHED_RAILING_B.get(),
                        blockregistry.DEEPSLATE_ARCHED_RAILING_C.get(),
                        blockregistry.DEEPSLATE_ARCHED_RAILING_D.get(),
                        blockregistry.DEEPSLATE_SIMPLE_RAILING_A.get(),
                        blockregistry.DEEPSLATE_SIMPLE_RAILING_B.get(),
                        blockregistry.DEEPSLATE_SIMPLE_RAILING_C.get(),
                        blockregistry.DEEPSLATE_SIMPLE_RAILING_D.get(),
                        blockregistry.MUD_BRICK_GLASS_RAILING_A.get(),
                        blockregistry.MUD_BRICK_ARCHED_RAILING_A.get(),
                        blockregistry.MUD_BRICK_SIMPLE_RAILING_A.get(),
                        blockregistry.LIMESTONE_STAIRS.get(),
                        blockregistry.DEEPSLATE_PILLAR.get(),
                        blockregistry.AMPHORA.get()
                );



        this.tag(BlockTags.NEEDS_IRON_TOOL)
                .add(
                        blockregistry.UNCUT_SAPPHIRE_PILLAR.get(),
                        blockregistry.UNCUT_RUBY_PILLAR.get(),
                        blockregistry.UNCUT_SAPPHIRE_NODE.get(),
                        blockregistry.UNCUT_MOONSTONE_PILLAR.get(),
                        blockregistry.UNCUT_MOONSTONE_NODE.get(),
                        blockregistry.UNCUT_RUBY_NODE.get(),
                        blockregistry.UNCUT_JADE_NODE.get(),
                        blockregistry.UNCUT_TOPAZ_NODE.get(),
                        blockregistry.UNCUT_JADE_PILLAR.get(),
                        blockregistry.UNCUT_TOPAZ_PILLAR.get(),
                        blockregistry.BRAZIER_MITHRIL.get(),
                        blockregistry.BRAZIER_ASTRALITE.get(),
                        blockregistry.BRAZIER_GLEAMIUM.get(),
                        blockregistry.BRAZIER_KYBER.get(),
                        blockregistry.BRAZIER_ORICHALCUM.get(),
                        blockregistry.BRAZIER_PROMETHEUM.get(),
                        blockregistry.BRAZIER_QUASARITE.get(),
                        blockregistry.BRAZIER_WYRMSTONE.get(),
                        blockregistry.RAW_MITHRIL_BLOCK.get(),
                        blockregistry.PROMETHEUM_BLOCK.get(),
                        blockregistry.PROMETHEUM_ORE.get(),
                        blockregistry.RAW_PROMETHEUM_BLOCK.get(),
                        blockregistry.QUASARITE_BLOCK.get(),
                        blockregistry.WYRMSTONE_BLOCK.get(),
                        blockregistry.ASTRALITE_BLOCK.get(),
                        blockregistry.RAW_ASTRALITE_BLOCK.get(),
                        blockregistry.SAPPHIRE_ALTAR.get(),
                        blockregistry.RUBY_ALTAR.get(),
                        blockregistry.JADE_ALTAR.get(),
                        blockregistry.TOPAZ_ALTAR.get(),
                        blockregistry.CROWN_ALTAR.get(),
                        blockregistry.TABLET_STAND.get(),
                        blockregistry.SILVER_ORE.get(),
                        blockregistry.DEEPSLATE_SILVER_ORE.get(),
                        blockregistry.SILVER_BLOCK.get(),
                        blockregistry.RAW_SILVER_BLOCK.get(),
                        blockregistry.SILVER_KALVIS_ALTAR.get(),
                        blockregistry.PROMETHEUM_KALVIS_ALTAR.get(),
                        blockregistry.GLEAMIUM_KALVIS_ALTAR.get(),
                        blockregistry.JANUS_TABLE.get(),
                        blockregistry.LIMESTONE_ARCHED_RAILING.get(),
                        blockregistry.LIMESTONE_SIMPLE_RAILING.get(),
                        blockregistry.LIMESTONE_GLASS_RAILING.get(),
                        blockregistry.DEEPSLATE_ARCHED_RAILING.get(),
                        blockregistry.DEEPSLATE_GLASS_RAILING.get(),
                        blockregistry.DEEPSLATE_GLASS_RAILING_A.get(),
                        blockregistry.DEEPSLATE_GLASS_RAILING_B.get(),
                        blockregistry.DEEPSLATE_GLASS_RAILING_C.get(),
                        blockregistry.DEEPSLATE_GLASS_RAILING_D.get(),
                        blockregistry.DEEPSLATE_SIMPLE_RAILING.get(),
                        blockregistry.ANDESITE_ARCHED_RAILING.get(),
                        blockregistry.ANDESITE_GLASS_RAILING.get(),
                        blockregistry.ANDESITE_SIMPLE_RAILING.get(),
                        blockregistry.BRICK_ARCHED_RAILING.get(),
                        blockregistry.BRICK_GLASS_RAILING.get(),
                        blockregistry.BRICK_SIMPLE_RAILING.get(),
                        blockregistry.MUD_BRICK_ARCHED_RAILING.get(),
                        blockregistry.MUD_BRICK_GLASS_RAILING.get(),
                        blockregistry.MUD_BRICK_SIMPLE_RAILING.get(),
                        blockregistry.STONE_ARCHED_RAILING.get(),
                        blockregistry.STONE_GLASS_RAILING.get(),
                        blockregistry.STONE_SIMPLE_RAILING.get(),
                        blockregistry.ANDESITE_GLASS_RAILING_A.get(),
                        blockregistry.ANDESITE_GLASS_RAILING_B.get(),
                        blockregistry.ANDESITE_GLASS_RAILING_C.get(),
                        blockregistry.ANDESITE_GLASS_RAILING_D.get(),
                        blockregistry.ANDESITE_GLASS_RAILING_E.get(),
                        blockregistry.ANDESITE_GLASS_RAILING_F.get(),
                        blockregistry.ANDESITE_GLASS_RAILING_G.get(),
                        blockregistry.ANDESITE_GLASS_RAILING_H.get(),
                        blockregistry.ANDESITE_GLASS_RAILING_I.get(),
                        blockregistry.ANDESITE_ARCHED_RAILING_A.get(),
                        blockregistry.ANDESITE_ARCHED_RAILING_B.get(),
                        blockregistry.ANDESITE_ARCHED_RAILING_C.get(),
                        blockregistry.ANDESITE_ARCHED_RAILING_D.get(),
                        blockregistry.ANDESITE_ARCHED_RAILING_E.get(),
                        blockregistry.ANDESITE_ARCHED_RAILING_F.get(),
                        blockregistry.ANDESITE_ARCHED_RAILING_G.get(),
                        blockregistry.ANDESITE_ARCHED_RAILING_H.get(),
                        blockregistry.ANDESITE_ARCHED_RAILING_I.get(),
                        blockregistry.ANDESITE_SIMPLE_RAILING_A.get(),
                        blockregistry.ANDESITE_SIMPLE_RAILING_B.get(),
                        blockregistry.ANDESITE_SIMPLE_RAILING_C.get(),
                        blockregistry.ANDESITE_SIMPLE_RAILING_D.get(),
                        blockregistry.ANDESITE_SIMPLE_RAILING_E.get(),
                        blockregistry.ANDESITE_SIMPLE_RAILING_F.get(),
                        blockregistry.ANDESITE_SIMPLE_RAILING_G.get(),
                        blockregistry.ANDESITE_SIMPLE_RAILING_H.get(),
                        blockregistry.ANDESITE_SIMPLE_RAILING_I.get(),
                        blockregistry.BRICK_GLASS_RAILING_A.get(),
                        blockregistry.BRICK_GLASS_RAILING_B.get(),
                        blockregistry.BRICK_GLASS_RAILING_C.get(),
                        blockregistry.BRICK_GLASS_RAILING_D.get(),
                        blockregistry.BRICK_GLASS_RAILING_E.get(),
                        blockregistry.BRICK_GLASS_RAILING_F.get(),
                        blockregistry.BRICK_GLASS_RAILING_G.get(),
                        blockregistry.BRICK_GLASS_RAILING_H.get(),
                        blockregistry.BRICK_GLASS_RAILING_I.get(),
                        blockregistry.BRICK_ARCHED_RAILING_A.get(),
                        blockregistry.BRICK_ARCHED_RAILING_B.get(),
                        blockregistry.BRICK_ARCHED_RAILING_C.get(),
                        blockregistry.BRICK_ARCHED_RAILING_D.get(),
                        blockregistry.BRICK_ARCHED_RAILING_E.get(),
                        blockregistry.BRICK_ARCHED_RAILING_F.get(),
                        blockregistry.BRICK_ARCHED_RAILING_G.get(),
                        blockregistry.BRICK_ARCHED_RAILING_H.get(),
                        blockregistry.BRICK_ARCHED_RAILING_I.get(),
                        blockregistry.BRICK_SIMPLE_RAILING_A.get(),
                        blockregistry.BRICK_SIMPLE_RAILING_B.get(),
                        blockregistry.BRICK_SIMPLE_RAILING_C.get(),
                        blockregistry.BRICK_SIMPLE_RAILING_D.get(),
                        blockregistry.BRICK_SIMPLE_RAILING_E.get(),
                        blockregistry.BRICK_SIMPLE_RAILING_F.get(),
                        blockregistry.BRICK_SIMPLE_RAILING_G.get(),
                        blockregistry.BRICK_SIMPLE_RAILING_H.get(),
                        blockregistry.BRICK_SIMPLE_RAILING_I.get(),
                        blockregistry.LIMESTONE_GLASS_RAILING_A.get(),
                        blockregistry.LIMESTONE_GLASS_RAILING_B.get(),
                        blockregistry.LIMESTONE_GLASS_RAILING_C.get(),
                        blockregistry.LIMESTONE_GLASS_RAILING_D.get(),
                        blockregistry.LIMESTONE_GLASS_RAILING_E.get(),
                        blockregistry.LIMESTONE_GLASS_RAILING_F.get(),
                        blockregistry.LIMESTONE_GLASS_RAILING_G.get(),
                        blockregistry.LIMESTONE_GLASS_RAILING_H.get(),
                        blockregistry.LIMESTONE_GLASS_RAILING_I.get(),
                        blockregistry.LIMESTONE_ARCHED_RAILING_A.get(),
                        blockregistry.LIMESTONE_ARCHED_RAILING_B.get(),
                        blockregistry.LIMESTONE_ARCHED_RAILING_C.get(),
                        blockregistry.LIMESTONE_ARCHED_RAILING_D.get(),
                        blockregistry.LIMESTONE_ARCHED_RAILING_E.get(),
                        blockregistry.LIMESTONE_ARCHED_RAILING_F.get(),
                        blockregistry.LIMESTONE_ARCHED_RAILING_G.get(),
                        blockregistry.LIMESTONE_ARCHED_RAILING_H.get(),
                        blockregistry.LIMESTONE_ARCHED_RAILING_I.get(),
                        blockregistry.LIMESTONE_SIMPLE_RAILING_A.get(),
                        blockregistry.LIMESTONE_SIMPLE_RAILING_B.get(),
                        blockregistry.LIMESTONE_SIMPLE_RAILING_C.get(),
                        blockregistry.LIMESTONE_SIMPLE_RAILING_D.get(),
                        blockregistry.LIMESTONE_SIMPLE_RAILING_E.get(),
                        blockregistry.LIMESTONE_SIMPLE_RAILING_F.get(),
                        blockregistry.LIMESTONE_SIMPLE_RAILING_G.get(),
                        blockregistry.LIMESTONE_SIMPLE_RAILING_H.get(),
                        blockregistry.LIMESTONE_SIMPLE_RAILING_I.get(),
                        blockregistry.STONE_GLASS_RAILING_A.get(),
                        blockregistry.STONE_GLASS_RAILING_B.get(),
                        blockregistry.STONE_GLASS_RAILING_C.get(),
                        blockregistry.STONE_ARCHED_RAILING_A.get(),
                        blockregistry.STONE_ARCHED_RAILING_B.get(),
                        blockregistry.STONE_ARCHED_RAILING_C.get(),
                        blockregistry.STONE_SIMPLE_RAILING_A.get(),
                        blockregistry.STONE_SIMPLE_RAILING_B.get(),
                        blockregistry.STONE_SIMPLE_RAILING_C.get(),
                        blockregistry.DEEPSLATE_ARCHED_RAILING_A.get(),
                        blockregistry.DEEPSLATE_ARCHED_RAILING_B.get(),
                        blockregistry.DEEPSLATE_ARCHED_RAILING_C.get(),
                        blockregistry.DEEPSLATE_ARCHED_RAILING_D.get(),
                        blockregistry.DEEPSLATE_SIMPLE_RAILING_A.get(),
                        blockregistry.DEEPSLATE_SIMPLE_RAILING_B.get(),
                        blockregistry.DEEPSLATE_SIMPLE_RAILING_C.get(),
                        blockregistry.DEEPSLATE_SIMPLE_RAILING_D.get(),
                        blockregistry.MUD_BRICK_GLASS_RAILING_A.get(),
                        blockregistry.MUD_BRICK_ARCHED_RAILING_A.get(),
                        blockregistry.MUD_BRICK_SIMPLE_RAILING_A.get(),
                        blockregistry.STONE_ARCHED_RAILING_D.get(),
                        blockregistry.STONE_ARCHED_RAILING_E.get(),
                        blockregistry.STONE_GLASS_RAILING_D.get(),
                        blockregistry.STONE_GLASS_RAILING_E.get(),
                        blockregistry.STONE_SIMPLE_RAILING_D.get(),
                        blockregistry.STONE_SIMPLE_RAILING_E.get(),
                        blockregistry.DEEPSLATE_PILLAR.get()

                );


        this.tag(BlockTags.NEEDS_DIAMOND_TOOL)
                .add(
                        blockregistry.DEEPSLATE_MITHRIL_ORE.get(),
                        blockregistry.MITHRIL_BLOCK.get(),
                        blockregistry.MITHRIL_ORE.get(),
                        blockregistry.ORICHALCUM_BLOCK.get(),
                        blockregistry.GLEAMIUM_BLOCK.get(),
                        blockregistry.RAW_GLEAMIUM_BLOCK.get(),
                        blockregistry.KYBER_BLOCK.get(),
                        blockregistry.KYBER_ORE.get(),
                        blockregistry.RAW_KYBER_BLOCK.get(),
                        blockregistry.ORICHALCUM_ORE.get(),
                        blockregistry.RAW_ORICHALCUM_BLOCK.get()
                );

        this.tag(BlockTags.NEEDS_STONE_TOOL)
                .add(blockregistry.LIMESTONE_STAIRS.get())
                ;

        this.tag(Tags.Blocks.NEEDS_NETHERITE_TOOL)
                ;

        this.tag(BlockTags.LOGS_THAT_BURN)
                .add(blockregistry.OLIVE_LOG.get())
                .add(blockregistry.OLIVE_WOOD.get())
                .add(blockregistry.STRIPPED_OLIVE_LOG.get())
                .add(blockregistry.STRIPPED_OLIVE_WOOD.get())
                .add(blockregistry.OLIVE_BEAM.get())
                .add(blockregistry.HAWTHORNE_LOG.get())
                .add(blockregistry.HAWTHORNE_WOOD.get())
                .add(blockregistry.STRIPPED_HAWTHORNE_LOG.get())
                .add(blockregistry.STRIPPED_HAWTHORNE_WOOD.get())
                .add(blockregistry.HAWTHORNE_BEAM.get());

        this.tag(BlockTags.PLANKS)
                .add(blockregistry.OLIVE_PLANKS.get())
                .add(blockregistry.HAWTHORNE_PLANKS.get());


        this.tag(BlockTags.MINEABLE_WITH_AXE)
                .add(blockregistry.OLIVE_LOG.get())
                .add(blockregistry.OLIVE_WOOD.get())
                .add(blockregistry.OLIVE_PLANKS.get())
                .add(blockregistry.STRIPPED_OLIVE_LOG.get())
                .add(blockregistry.STRIPPED_OLIVE_WOOD.get())
                .add(blockregistry.OLIVE_BEAM.get())
                .add(blockregistry.OLIVE_PALISADE.get())
                .add(blockregistry.SCROLL.get())
                .add(blockregistry.OLIVE_PLANKS.get())
                .add(blockregistry.HAWTHORNE_LOG.get())
                .add(blockregistry.HAWTHORNE_WOOD.get())
                .add(blockregistry.HAWTHORNE_PLANKS.get())
                .add(blockregistry.STRIPPED_HAWTHORNE_LOG.get())
                .add(blockregistry.STRIPPED_HAWTHORNE_WOOD.get())
                .add(blockregistry.HAWTHORNE_BEAM.get())
                .add(blockregistry.HAWTHORNE_PALISADE.get())
                .add(blockregistry.OLIVE_STAIRS.get())
                .add(blockregistry.OLIVE_SLAB.get())
                .add(blockregistry.OLIVE_BUTTON.get())
                .add(blockregistry.OLIVE_PRESSURE_PLATE.get())
                .add(blockregistry.OLIVE_FENCE.get())
                .add(blockregistry.OLIVE_FENCE_GATE.get())
                .add(blockregistry.OLIVE_DOOR.get())
                .add(blockregistry.OLIVE_TRAPDOOR.get())
                .add(blockregistry.HAWTHORNE_STAIRS.get())
                .add(blockregistry.HAWTHORNE_SLAB.get())
                .add(blockregistry.HAWTHORNE_BUTTON.get())
                .add(blockregistry.HAWTHORNE_PRESSURE_PLATE.get())
                .add(blockregistry.HAWTHORNE_FENCE.get())
                .add(blockregistry.HAWTHORNE_FENCE_GATE.get())
                .add(blockregistry.HAWTHORNE_DOOR.get())
                .add(blockregistry.HAWTHORNE_TRAPDOOR.get());
        this.tag(BlockTags.MINEABLE_WITH_SHOVEL)
                .add(blockregistry.SALT_BLOCK.get());


        this.tag(BlockTags.FENCES)
                .add(blockregistry.HAWTHORNE_FENCE.get())
                .add(blockregistry.OLIVE_FENCE.get());
        this.tag(BlockTags.FENCE_GATES)
                .add(blockregistry.HAWTHORNE_FENCE_GATE.get())
                .add(blockregistry.OLIVE_FENCE_GATE.get());


    }
}